version: "3.8"

services:
  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./srednje-programi.json:/srv/srednje-programi.json:ro
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - default
    depends_on:
      engine:
        condition: service_healthy

  engine:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - default
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "https://engine.eduformacije.com/api/v1/status" ]
      interval: 10s
      timeout: 5s
      retries: 5

  mongo:
    image: mongo
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=adminUser123
      - MONGO_INITDB_ROOT_PASSWORD=jakaSifra123
    networks:
      - default
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh --quiet
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:6.2.6
    restart: unless-stopped
    volumes:
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    sysctls:
      net.core.somaxconn: "65535"
    networks:
      - default
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "StrongRedisPassword123", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongo_data:
  redis_data:
  caddy_data:
  caddy_config:

networks:
  default:
    driver: bridge
