version: '3.8'
services:
  engine:
    build: .
    ports:
      - "80:80" # Izloži port 80 na host mašini na port 80 u kontejneru
      - "443:443" # Dodano za HTTPS, ali zahteva konfiguraciju SSL certifikata
      # load env variables from .env file
    env_file:
      - .env
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mongo_data:
  redis_data:
